### ISSUE TITLE
WPFButtonBase の EmulateClick と IsEnabled について

### ISSUE THREAD

**Issue by YoshihiroIto** [Roommetro/Friendly.WPFStandardControls#1]
WPFButtonBase の EmulateClick と IsEnabled について質問があります。

WPFButtonBase  が示すボタンがIsEnabled==false であるときに
EmulateClick を実行するとそのボタンの Clickイベントやバインディングしているコマンドが実行されます。

GUI上にマウスカーソルを持ってきて左クリックした際の振る舞いを基準に考えると、
（私の）感覚ではIsEnabledがfalseなのでクリックできないのでクリックイベントが発火するのは不自然に思えます。

質問は

１）
この振る舞いはこういうものでしょうか？

２）
この振る舞いが狙い通りであるのであれば、
ユーザー側でEmulateClick をラップして IsEnabled を考慮するものを用意するという対処で問題ないでしょうか？

よろしくお願いいたします。

**Comment by Ishikawa-Tatsuya** [comment]
ご指摘ありがとうございます。

回答いたします。

１）この振る舞いはこういうものでしょうか？
はい。そういうものです。
でも不自然ではありますね。
とは言え、Friendlyでは他のContorlの処理も有効無効判別してません。
(WPFのメニューだけ別だったかも）

２）ユーザー側でEmulateClick をラップして
問題ありません。

ご質問のケースの場合、私が書くならケースを分けて書きます。
（そのためこの振る舞いで問題なく使ってきました）
・Aの状態の時にボタンが無効であること
・ボタンを押すとBの処理が実行されること

言われてみれば不自然なので、ここは変更するかもしれません。
（変更しても大部分のテストには影響しないので）
とは言え、直近ではそのままなので、ご提案のようにラップしてご利用お願いします。

よろしくお願いします。

**Comment by YoshihiroIto** [comment]
早々のご回答ありがとうございます。
現仕様ということで理解しました。

# Friendly の存在は知っていたもののなかなか手が出せていなかったのですが、いざ試してみるとその強力さをすぐに感じられました。ガッツリ利用させていただきます。ありがとうございます。
