### ISSUE TITLE
Runtime error while running WPF application using RM.Friendly.WPFStandardControls. in .Net version 4.6.1

### ISSUE THREAD

**Issue by gourish2k** [Roommetro/Friendly.WPFStandardControls#3]
Hello,

I am running a application which uses Prism Bootstrapper to load the modules.
On loading of the module dll RM.Friendly.WPFStandardControls.dll I get the following error.

> Caught exception at the Application level System.TypeLoadException: GenericArguments[0], 'CoreType', on 'RM.Friendly.WPFStandardControls.WPFControlBase`1[CoreType]' violates the constraint of type parameter 'CoreType'.

I guess it is because RM.Friendly does not support .Net Version 4.6.1.  RM.Friendly is built with .Net version 4.0 and Prism required .Net version of 4.5.0

Is there anything I need to do to make it work with version 4.6.1.

Thanks

**Comment by gourish2k** [comment]
The issue was resolved by using the AddModule method to import only the required module using Prism Bootstrapper.  Earlier by default all the dlls in the directories were getting loaded, so when the application tried to load the RM.Friendly.WPFStandardControls.dll dll the error was raised.

**Comment by Ishikawa-Tatsuya** [comment]
I am sorry that I could not check the issue. (I noticed today)
Thank you for using Friendly! I am glad that the problem was solved.
